name: init
description: Setup Node.js environment and install dependencies
runs:
  using: composite
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        check-latest: true
        node-version-file: package.json

    - name: Install dependencies
      run: npm ci
      shell: bash
